"""Business Model and other changes

Revision ID: 7c1d011842dd
Revises: 603bf85940f0
Create Date: 2025-01-13 23:06:36.827758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1d011842dd'
down_revision = '603bf85940f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_gst_registered', sa.Boolean(), nullable=False),
    sa.Column('gst_number', sa.String(length=20), nullable=True),
    sa.Column('pan_number', sa.String(length=10), nullable=True),
    sa.Column('terms_and_conditions', sa.Text(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('industry_type_id', sa.Integer(), nullable=True),
    sa.Column('business_registration_type_id', sa.Integer(), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_registration_type_id'], ['business_registration_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['industry_type_id'], ['industry_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('gst_number'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pan_number'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('user_business',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'business_id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('person_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('person_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('person_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('person_addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('measuring_units', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('business_id')

    op.drop_table('user_business')
    op.drop_table('businesses')
    # ### end Alembic commands ###
