"""business_id field dropped

Revision ID: ab1a348c1cc6
Revises: 09fa19708e90
Create Date: 2025-01-14 12:52:59.496624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1a348c1cc6'
down_revision = '09fa19708e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_business_id_fkey', type_='foreignkey')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('users_business_id_fkey', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
